@startuml myIndrata
!define DARKRED
!includeurl https://raw.githubusercontent.com/myindrata/RedDress-PlantUML/master/style.puml

class myClass{
    -int count
    #int number
    +String Name
    --
    ~methodOne()
    methodTwo()
}

class secondClass{
int aSecretField
void secretMetod()
}

@enduml